### ISSUE TITLE
warning when opening schematic in KiCad 5.1

### ISSUE THREAD

**Issue by pdp7** [oshwabadge2020/Badge-PCB#1]
I got a warning when opening in KiCad 5.1 that the schematic was made using older symbol libraries which may break the schematic.  The reference was U1: W25Q128JVS

Here is screenshot:
Image: https://photos.app.goo.gl/DeDS7NZ7dhekTugQ7

I just thought I would check to see if this is an issue.

thanks,
drew

**Comment by morganrallen** [comment]
This is also likely why the models aren't loading as per your .io post. Was this started in an older version of KiCAD? 4.0.7 maybe
