### ISSUE TITLE
0603 capacitor specified for a 0402 pattern

### ISSUE THREAD

**Issue by mwelling** [oshwabadge2020/Badge-PCB#27]
https://github.com/oshwabadge2020/Badge-PCB/blob/master/badge.csv#L4

For the 10uF capacitors we have an 0402 footprint and an 0603 component specified in the BOM.

**Comment by pdp7** [comment]
I am emailing kevin at digikey about this

**Comment by mwelling** [comment]
We need to change the BOM inside the project to reflect an 0402 component.

**Comment by pdp7** [comment]
@mwelling What do you think of this one?

311-1729-1-ND
CAP CER 10UF 6.3V X5R 0402 +/- 20%
https://www.digikey.com/product-detail/en/yageo/CC0402MRX5R5BB106/311-1729-1-ND/5195631

**Comment by pdp7** [comment]
> Subject: OHSummit: change 10UF cap from 0603 to 0402
> To: Kevin Walseth
> 
> Hi Kevin,
> 
> Sorry for the trouble, but we got this wrong in the BoM.
> 
> Qty 6 of 10 uF (C15 C3 C4 C5 C6 C7) should be 0402 but instead we
specified 0603:
> 
> 311-1781-1-ND
> CAP CER 10UF 6.3V X5R 0603 +/- 10%
https://www.digikey.com/product-detail/en/yageo/CC0603KRX5R5BB106/311-1781-1-ND/5195683
> 
> Could you ship 0402 version instead to SparkFun?
> 
> Maybe this one which is 0402?
> 
> 311-1729-1-ND
> CAP CER 10UF 6.3V X5R 0402 +/- 20%
https://www.digikey.com/product-detail/en/yageo/CC0402MRX5R5BB106/311-1729-1-ND/5195631
> 
> 
> Thanks,
> Drew

**Comment by mwelling** [comment]
Looks good to me.
