### ISSUE TITLE
layout: single board or 2 stacked boards?

### ISSUE THREAD

**Issue by pdp7** [oshwabadge2020/Badge-PCB#5]
I see that @mwelling is experimenting with a two board design based on the initial design by @acamilo.

Alex / Michael - do you think this will increase the complexity for SparkFun to assemble?  could we get away with one board, or do we have too many features to pack in to that space?

@nseidle @npoole would two boards for the OHS wristwatch badge be acceptable for sparkfun assembly? 

thanks!

**Comment by mwelling** [comment]
The boards will be a single assembly connected by mouse bites. It should not be any more difficult to assemble than a single board.

**Comment by pdp7** [comment]
fyi - from the project chat:
[Stacking boards and wrist mounting options](
https://hackaday.io/project/168483-open-hardware-summit-2020-badge/log/172231-stacking-boards-and-wrist-mounting-options)
