### ISSUE TITLE
Schematic: TFT part not found

### ISSUE THREAD

**Issue by pdp7** [oshwabadge2020/Badge-PCB#6]
@mwelling @acamilo I get this error when opening the schematic:
https://drive.google.com/file/d/1yV3evtUtcjzEU9EdJwjOczyqiNKNChYE/view?usp=sharing
https://drive.google.com/file/d/1z54ayqx_C5wUFP1OZ-xiHHbq0OHI8Zy6/view?usp=sharing

**Comment by mwelling** [comment]
You just need to change to a relative path in the library path. 

Lemme fix it on my fork.

**Comment by mwelling** [comment]
https://github.com/mwelling/Badge-PCB/commit/2f8b797bd9968c6d512afe70e5037b96edf8f7c1
